checkClassfyNum:
  labortory:
    - '其他检查'
    - '血液检查'
    - '尿液检查'
    - '粪便检查'
    - '精液检查'
    - '胸水检查'
    - '腹水检查'
    - '脑脊液检查'

  picture:
    - '其他检查'
    - '超声检查'
    - 'X线或X线造影检查'
    - 'CT检查'
    - '磁共振（MRI）检查'
    - '同位素（核素）检查'
    - 'PET-CT检查'

  invasive:
    - '其他检查'
    - '胃镜检查'
    - '肠镜检查'
    - '喉镜检查'
    - '鼻窦镜检查'
    - '支气管检查'
    - '膀胱尿道镜检查'
    - '阴道镜检查'
    - '宫腔镜检查'

  pathology:
    - '其他检查'
    - '活组织检查'

  other:
    - '其他检查'
    - '其他检查'